name: pausable_timer
description: A timer that can be paused, resumed and reset.
version: 0.1.0

dependencies:
  clock: '^1.0.1'

dev_dependencies:
  test: '^1.15.2'
  pedantic: '^1.9.0'
  fake_async: '^1.0.1'
