name: pausable_timer
description: A timer implementation that can be paused, resumed and reset.
homepage: https://github.com/llucax/pausable_timer
repository: https://github.com/llucax/pausable_timer

version: 0.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  clock: '^1.0.1'

dev_dependencies:
  coverage: '^0.14.1'
  test: '^1.15.2'
  pedantic: '^1.9.0'
  fake_async: '^1.0.1'
