name: Latest Dart Version

on:
  schedule:
    - cron: '0 6 * * 5' # Run at 6:00 on Friday

env:
  # Current supported major
  major: 2
  # Latest minor that we are explicitly supporting
  latest_minor: 13

jobs:
  check-dart-version:
    name: Check
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: sudo apt update && sudo apt install curl jq

    - name: Check latest version ${{ env.major }} docker image
      run: |
        digest() {
          curl -s -H "Content-Type: application/json" "https://hub.docker.com/v2/repositories/google/dart/tags/$1" |
            jq .images[0].digest
        }
        if test "$(digest $major)" != "$(digest $major.$latest_minor)"
        then
          echo "Version of $major.$latest_minor is not the latest version" \
            "$major for https://hub.docker.com/r/google/dart" >&2
            exit 1
        fi

# vim: set et sw=2 sts=2 :
