name: Latest Dart Version

on:
  schedule:
    - cron: '0 6 * * 5' # Run at 6:00 on Friday

env:
  # Current supported major
  major: 2
  # Latest minor that we are explicitly supporting
  latest_minor: 13

jobs:
  check-dart-version:
    name: Check
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: sudo apt update && sudo apt install curl jq

    - name: Check latest version ${{ env.major }} docker image
      run: |
        digest() {
          curl -s -H "Content-Type: application/json" "https://hub.docker.com/v2/repositories/_/dart/tags/$1" |
            jq .images[0].digest
        }
        digest_stable=$(digest stable)
        digest_current=$(digest $major.$latest_minor)
        if test "$digest_stable" = null -o "$digest_current" = null
        then
          echo "Could not get the stable image digest ($digest_stable) or the currrent ($major.$latest_minor)" \
            "image digest ($digest_current)." >&2
            exit 1
        fi
        if test "$digest_stable" != "$digest_current"
        then
          echo "Version of $major.$latest_minor is not the latest stable" \
            "version for https://hub.docker.com/r/_/dart" >&2
            exit 1
        fi

# vim: set et sw=2 sts=2 :
