name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image:  google/dart:2.10

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: dart pub get

    # Analyze step needs different config for pull_request and push, so it is
    # duplicated with if conditions to use the correct configuration for each
    - name: Analyze (push)
      if: ${{ github.event_name == 'push' }}
      uses: kitek/dartanalyzer-annotations-action@v1  
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        check_name: test
        commit_sha: ${{ github.sha }}
    - name: Analyze (pull_request)
      if: ${{ github.event_name == 'pull_request' }}
      uses: kitek/dartanalyzer-annotations-action@v1  
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        check_name: test
        commit_sha: ${{ github.event.pull_request.head.sha }}

    - name: Check format
      run: dart format --summary none --set-exit-if-changed -o none
        lib test example

    - name: Run tests
      run: dart test --coverage=./coverage

    - name: Convert coverage to LCOV
      run: dart pub run coverage:format_coverage --lcov --packages=.packages
        --report-on=lib -i coverage -o coverage/lcov.info

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: coverage/lcov.info
        flags: unit

# vim: set et sw=2 sts=2 :
